"""
config.py
=========
Single source of truth for every path and setting used across the project.
No module hardcodes a relative path like "../data/..." — everything is
resolved from PROJECT_ROOT so scripts work identically whether run from
the repo root, from src/, or imported from anywhere else.
"""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

# ---------------------------------------------------------------------------
# Raw data (downloaded / scraped — not tracked in git)
# ---------------------------------------------------------------------------
DATA_RAW_DIR = PROJECT_ROOT / "data" / "raw"
TRAIN_SOURCE_DIR = DATA_RAW_DIR / "football_golden_foot"   # one subfolder per player
TEST_SOURCE_DIR = DATA_RAW_DIR / "test"                    # supplementary test images

# Kaggle datasets
KAGGLE_TRAIN_DATASET = "balabaskar/golden-foot-football-players-image-dataset"
KAGGLE_TEST_DATASET = "azizbali/football-players-faces-dataset"

# ---------------------------------------------------------------------------
# Processed data (generated by the pipeline — not tracked in git)
# ---------------------------------------------------------------------------
DATA_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

CROPPED_FACES_DIR = DATA_PROCESSED_DIR / "cropped_faces"
RESIZED_FACES_DIR = DATA_PROCESSED_DIR / "resized_faces"
AUGMENTED_DIR = DATA_PROCESSED_DIR / "augmented"
SPLITS_DIR = DATA_PROCESSED_DIR / "splits"
TRAIN_SPLIT_DIR = SPLITS_DIR / "train"
VAL_SPLIT_DIR = SPLITS_DIR / "val"
TEST_READY_DIR = DATA_PROCESSED_DIR / "test_ready"

# ---------------------------------------------------------------------------
# Face detection / preprocessing
# ---------------------------------------------------------------------------
XML_DIR = PROJECT_ROOT / "XML"
HAAR_FACE_CASCADE = XML_DIR / "haarcascade_frontalface_default.xml"
HAAR_EYE_CASCADE = XML_DIR / "haarcascade_eye.xml"

FACE_SIZE = (160, 160)  # required input size for FaceNet (InceptionResnetV1)
N_AUGMENTED_COPIES = 3  # extra augmented copies generated per original image

# ---------------------------------------------------------------------------
# Embeddings / model
# ---------------------------------------------------------------------------
FACENET_PRETRAINED = "vggface2"

MODELS_DIR = PROJECT_ROOT / "models"
EMBEDDINGS_DIR = MODELS_DIR / "embeddings"
TRAIN_EMB_PREFIX = EMBEDDINGS_DIR / "train"
VAL_EMB_PREFIX = EMBEDDINGS_DIR / "val"
TEST_EMB_PREFIX = EMBEDDINGS_DIR / "test"
CLASSES_NPY = EMBEDDINGS_DIR / "classes.npy"

SVM_MODEL_PATH = MODELS_DIR / "svm_classifier.joblib"

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------
OUTPUT_FIGURES_DIR = PROJECT_ROOT / "outputs" / "figures"
OUTPUT_METRICS_DIR = PROJECT_ROOT / "outputs" / "metrics"

# ---------------------------------------------------------------------------
# Reproducibility
# ---------------------------------------------------------------------------
SEED = 42
VAL_SIZE = 0.15
